---
- name: Validate required variables
  assert:
      that:
          - packages is defined and packages | length > 0
          - azure_resource_group is defined
          - azure_storage_account_name is defined
          - azure_container_name is defined
      fail_msg: "One or more required variables are missing or invalid."

- name: Create Azure Blob Storage container
  azure_rm_storageblob:
      resource_group: "{{ azure_resource_group }}"
      storage_account_name: "{{ azure_storage_account_name }}"
      container: "{{ azure_container_name }}"
      state: present

- name: Upload nupkg files to Azure Blob Storage
  azure_rm_storageblob:
      resource_group: "{{ azure_resource_group }}"
      storage_account_name: "{{ azure_storage_account_name }}"
      container: "{{ azure_container_name }}"
      blob: "{{ item | basename }}"
      src: "{{ item }}"
      public_access: container
      content_type: "application/zip"
  loop: "{{ lookup('fileglob', destination_dir + '/*.nupkg', wantlist=True) }}"
  loop_control:
      label: "{{ item | basename }}"
